# Lista 003: Lista Sequencial

In [12]:
import numpy as np

class ListaSequencial:
    def __init__(self, capacidade: int):
        self.capacidade: int = capacidade
        self.valores: np.ndarray = np.empty(self.capacidade, dtype=int)
        self.ultima_posicao: int = -1

    def insere(self, valor: int):
        if self.ultima_posicao == self.capacidade - 1:
            print('Capacidade máxima atingida')
        else:
            self.ultima_posicao += 1
            self.valores[self.ultima_posicao] = valor

    def pesquisar(self, valor: int):
        for i in range(0, self.ultima_posicao + 1):
            if self.valores[i] == valor:
                return i
        return -1

    def excluir(self, valor: int):
        posicao = self.pesquisar(valor)
        if posicao == -1:
            return -1
        else:
            for i in range(posicao, self.ultima_posicao):
                self.valores[i] = self.valores[i + 1]
            self.ultima_posicao -= 1

    def imprime(self):
        if self.ultima_posicao == -1:
            print("O vetor está vazio")
        else:
            for i in range(self.ultima_posicao + 1):
                print(f"{i} - {self.valores[i]}")

1. Crie uma lista sequencial com capacidade para 5 elementos. Insira as matrículas dos seguintes alunos: 101, 102, 103, 104. Depois, imprima a lista para verificar os valores armazenados.

In [2]:
lista = ListaSequencial(5)
lista.insere(101)
lista.insere(102)
lista.insere(103)
lista.insere(104)
lista.imprime()

0 - 101
1 - 102
2 - 103
3 - 104


2. Uma loja deseja registrar os códigos dos produtos em estoque. Insira os códigos 45, 33, 27, 89, 56 em uma lista sequencial de capacidade 5.
Depois, tente inserir o produto 72 e observe o que acontece.

In [3]:
lista = ListaSequencial(5)
lista.insere(45)
lista.insere(33)
lista.insere(27)
lista.insere(89)
lista.insere(56)
lista.imprime()
lista.insere(72)

0 - 45
1 - 33
2 - 27
3 - 89
4 - 56
Capacidade máxima atingida


3. Considere que foram cadastrados os clientes com os códigos 11, 22, 33, 44, 55. Pesquise se o cliente com código 33 está presente e informe sua posição na lista.

In [4]:
lista = ListaSequencial(5)
lista.insere(11)
lista.insere(22)
lista.insere(33)
lista.insere(44)
lista.insere(55)
posicao = lista.pesquisar(33)
if posicao != -1:
    print(f"O cliente com código 33 está na posição {posicao}")
else:
    print("O cliente com código 33 não está na lista")

O cliente com código 33 está na posição 2


4. A lista de clientes contém os códigos: 10, 20, 30, 40, 50. Exclua o cliente com código 30 e imprima a lista para verificar se a exclusão foi realizada corretamente.

In [5]:
lista = ListaSequencial(5)
lista.insere(10)
lista.insere(20)
lista.insere(30)
lista.insere(40)
lista.insere(50)
lista.imprime()
lista.excluir(30)
lista.imprime()

0 - 10
1 - 20
2 - 30
3 - 40
4 - 50
0 - 10
1 - 20
2 - 40
3 - 50


5. Pacientes aguardam atendimento e foram cadastrados os números de senha: 5, 6, 7, 8, 9. Um paciente desistiu (senha 7). Faça a exclusão deste paciente e imprima novamente a lista.

In [6]:
lista = ListaSequencial(5)
lista.insere(5)
lista.insere(6)
lista.insere(7)
lista.insere(8)
lista.insere(9)
lista.imprime()
lista.excluir(7)
lista.imprime()

0 - 5
1 - 6
2 - 7
3 - 8
4 - 9
0 - 5
1 - 6
2 - 8
3 - 9


6. O hotel tem capacidade para 6 reservas. Insira os números de reserva: 101, 103, 107, 110, 115. Depois, pesquise se a reserva 108 já foi cadastrada e mostre a resposta.

In [7]:
lista = ListaSequencial(6)
lista.insere(101)
lista.insere(103)
lista.insere(107)
lista.insere(110)
lista.insere(115)
posicao = lista.pesquisar(108)
if posicao != -1:
    print(f"A reserva 108 está na posição {posicao}")
else:
    print("A reserva 108 não está cadastrada")

A reserva 108 não está cadastrada


7. Foram cadastrados os pedidos: 2001, 2002, 2003, 2004, 2005. O cliente cancelou o pedido 2002. Exclua-o e imprima a lista atualizada.

In [8]:
lista = ListaSequencial(5)
lista.insere(2001)
lista.insere(2002)
lista.insere(2003)
lista.insere(2004)
lista.insere(2005)
lista.excluir(2002)
lista.imprime()

0 - 2001
1 - 2003
2 - 2004
3 - 2005


8. Em um estacionamento cabem 4 carros. Insira as placas (numéricas fictícias): 1234, 5678, 9101, 1213. Verifique se a placa 5678 está estacionada. Depois, tente inserir a placa 1415. O que acontece?

In [9]:
lista = ListaSequencial(4)
lista.insere(1234)
lista.insere(5678)
lista.insere(9101)
lista.insere(1213)
posicao = lista.pesquisar(5678)
if posicao != -1:
    print(f"A placa 5678 está estacionada na posição {posicao}")
else:
    print("A placa 5678 não está estacionada")
lista.insere(1415)

A placa 5678 está estacionada na posição 1
Capacidade máxima atingida


9. Considere uma lista com as notas: 70, 85, 90, 75, 60. Pesquise se o aluno obteve a nota 75 e indique a posição encontrada.

In [10]:
lista = ListaSequencial(5)
lista.insere(70)
lista.insere(85)
lista.insere(90)
lista.insere(75)
lista.insere(60)
posicao = lista.pesquisar(75)
if posicao != -1:
    print(f"O aluno obteve a nota 75 na posição {posicao}")
else:
    print("O aluno não obteve a nota 75")

O aluno obteve a nota 75 na posição 3


10. Uma lista contém os valores: 1, 2, 3, 4, 5, 6. Exclua os valores 3 e 5, um de cada vez, e mostre a lista após cada exclusão.

In [11]:
lista = ListaSequencial(6)
lista.insere(1)
lista.insere(2)
lista.insere(3)
lista.insere(4)
lista.insere(5)
lista.insere(6)
lista.excluir(3)
lista.imprime()
lista.excluir(5)
lista.imprime()

0 - 1
1 - 2
2 - 4
3 - 5
4 - 6
0 - 1
1 - 2
2 - 4
3 - 6
